// System Constants
const ROLES = {
  ADMIN: 'ADMIN',
  SUPERVISOR: 'SUPERVISOR',
  ASHA: 'ASHA'
};

const RISK_FLAGS = {
  NORMAL: 'NORMAL',
  NEEDS_FOLLOW_UP: 'NEEDS_FOLLOW_UP',
  HIGH_PRIORITY: 'HIGH_PRIORITY'
};

const REFERRAL_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED'
};

const VISIT_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  MISSED: 'MISSED'
};

const VISIT_TYPES = {
  PREGNANCY_ANC: 'PREGNANCY_ANC',
  POSTNATAL_PNC: 'POSTNATAL_PNC',
  CHILD_IMMUNIZATION: 'CHILD_IMMUNIZATION',
  CHILD_GROWTH: 'CHILD_GROWTH',
  MEDICINE_DISTRIBUTION: 'MEDICINE_DISTRIBUTION',
  GENERAL_FAMILY: 'GENERAL_FAMILY',
  ELDERLY_CARE: 'ELDERLY_CARE'
};

const MEDICINE_STATUS = {
  AVAILABLE: 'AVAILABLE',
  LOW_STOCK: 'LOW_STOCK',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  EXPIRING_SOON: 'EXPIRING_SOON',
  EXPIRED: 'EXPIRED'
};

const NOTIFICATION_PRIORITY = {
  URGENT: 'URGENT',
  HIGH: 'HIGH',
  NORMAL: 'NORMAL',
  INFO: 'INFO'
};

const TASK_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

const MODULES = {
  PREGNANCY: 'PREGNANCY',
  CHILD: 'CHILD',
  MEDICINE: 'MEDICINE',
  VISIT: 'VISIT',
  REFERRAL: 'REFERRAL',
  FAMILY: 'FAMILY',
  WORKER: 'WORKER',
  SYSTEM: 'SYSTEM'
};

module.exports = {
  ROLES,
  RISK_FLAGS,
  REFERRAL_STATUS,
  VISIT_STATUS,
  VISIT_TYPES,
  MEDICINE_STATUS,
  NOTIFICATION_PRIORITY,
  TASK_STATUS,
  MODULES
};
